### ISSUE TITLE
Add fine tuning to zombie spawners

### ISSUE THREAD

**Issue by maximwebb** [maximwebb/ellas-vs-maxims#22]
We need to have the following parameters for customising the zombie spawners:

- Time delay before first zombie spawns
- Which lanes zombies spawn in
- The type of zombies (reliant on different zombie types being added in the future)
- The frequency of zombie spawn (ease in, ease out etc.)
- The total number of zombies to be spawned (as well as an endless option)

**Comment by tatiana-s** [comment]
Just an idea and might be unhandy, but especially with having several levels in the future it might be good to be able to input parameters such as these as a seperate file (e.g JSON parsing)

**Comment by maximwebb** [comment]
> Just an idea and might be unhandy, but especially with having several levels in the future it might be good to be able to input parameters such as these as a seperate file (e.g something like JSON parsing)

I reckon this would be a good idea, but perhaps a second constructor could be added so that simple waves can quickly be created, without the need for a full JSON file detailing every aspect of the zombie wave.
