### ISSUE TITLE
Add support for animations

### ISSUE THREAD

**Issue by maximwebb** [maximwebb/ellas-vs-maxims#36]

**Comment by BananaGrandmaster** [comment]
If we're gonna do this we should probably make a Sprite class (something we discussed previously) and then each RenderedGameObject would have a list of instances of this class.
Also are we gonna do animation by cycling through different images (each a different sprite) or by moving sprites (e.g. sprites for arms and legs which move alongside the body)?

**Comment by HelgeGH** [comment]
If we chose to do animation by cycling through different images, we can create an AnimationHandler class where you initialise it with some name (eg. "eggplant")  (which can be used to fetch the .png files if they are called eggplant001, eggplant002 etc.) and the number of images each animation cycle consists of. Then you write something along the lines of "this.sprite = AnimationHandler.nextSprite()" in each "update()".
